http_server:
  address: "banner-service:8080"
postgres:
  db_name: "bannerDB"
  db_pass: "12345"
  db_host: "postgres"
  db_port: 5432
  db_user: "root"
redis:
  address: "cache:6379"
  cache_pass: "67890"